In [76]:
#libararies
import pandas as pd
import numpy as np
import seaborn as sns
from datetime import datetime

In [77]:
#loading data
df = pd.read_csv("../data/Gemini_BTCUSD_1h.csv")

In [78]:
#peaking into data
df.head()

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USD
0,1.716850e+12,2024-05-27 23:00,BTC/USD,69530.96,69530.96,69262.93,69359.11,4.704225,326280.8294
1,1.716850e+12,2024-05-27 22:00,BTC/USD,69738.00,69738.00,69505.21,69530.96,3.516792,244525.9294
2,1.716840e+12,2024-05-27 21:00,BTC/USD,69573.92,69738.00,69532.02,69738.00,2.656408,185252.5525
3,1.716840e+12,2024-05-27 20:00,BTC/USD,69177.77,69643.26,69120.37,69573.92,5.652349,393256.0556
4,1.716840e+12,2024-05-27 19:00,BTC/USD,69900.83,70014.64,69035.13,69177.77,13.942192,964489.7812

In [79]:
#looking at columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75704 entries, 0 to 75703
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   unix        75704 non-null  float64
 1   date        75704 non-null  object
 2   symbol      75704 non-null  object
 3   open        75704 non-null  float64
 4   high        75704 non-null  float64
 5   low         75704 non-null  float64
 6   close       75704 non-null  float64
 7   Volume BTC  75704 non-null  float64
 8   Volume USD  75704 non-null  float64
dtypes: float64(7), object(2)
memory usage: 5.2+ MB

In [80]:
#converting float to 64bit int values
df['unix'] = df['unix'].astype(np.int64)

upon looking at the data for the first 51873 rows the unix timestamps were in milliseconds while after that seconds were used

In [82]:
#sanity check
df.head(51877)

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USD
0,1716850000000,2024-05-27 22:46:40.000,BTC/USD,69530.96,69530.96,69262.93,69359.11,4.704225,326280.8294
1,1716850000000,2024-05-27 22:46:40.000,BTC/USD,69738.00,69738.00,69505.21,69530.96,3.516792,244525.9294
2,1716840000000,2024-05-27 20:00:00.000,BTC/USD,69573.92,69738.00,69532.02,69738.00,2.656408,185252.5525
3,1716840000000,2024-05-27 20:00:00.000,BTC/USD,69177.77,69643.26,69120.37,69573.92,5.652349,393256.0556
4,1716840000000,2024-05-27 20:00:00.000,BTC/USD,69900.83,70014.64,69035.13,69177.77,13.942192,964489.7812
...,...,...,...,...,...,...,...,...,...
51872,1530100000000,2018-06-27 11:46:40.000,BTC/USD,6092.20,6092.20,6060.11,6088.28,39.638066,241327.6460
51873,1530100000000,2018-06-27 11:46:40.000,BTC/USD,6117.70,6117.70,6081.20,6092.20,37.718513,229788.7253
51874,1530093600,1970-01-18 17:01:33.600,BTC/USD,6095.42,6131.08,6085.82,6117.70,25.943567,158714.9615
51875,1530090000,1970-01-18 17:01:30.000,BTC/USD,6080.23,6105.65,6074.40,6095.42,18.003647,109739.7880
51876,1530086400,1970-01-18 17:01:26.400,BTC/USD,6075.92,6109.00,6065.84,6080.23,26.453684,160844.4850

In [81]:
#converting epoch time to local time
df['date'] = pd.to_datetime(df['unix'], unit='ms')

In [83]:
#dropping epoch time necause it has been converted
#df = df.drop(columns=['unix']).copy()

In [84]:
#Sanity Check
df.head()

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USD
0,1716850000000,2024-05-27 22:46:40,BTC/USD,69530.96,69530.96,69262.93,69359.11,4.704225,326280.8294
1,1716850000000,2024-05-27 22:46:40,BTC/USD,69738.00,69738.00,69505.21,69530.96,3.516792,244525.9294
2,1716840000000,2024-05-27 20:00:00,BTC/USD,69573.92,69738.00,69532.02,69738.00,2.656408,185252.5525
3,1716840000000,2024-05-27 20:00:00,BTC/USD,69177.77,69643.26,69120.37,69573.92,5.652349,393256.0556
4,1716840000000,2024-05-27 20:00:00,BTC/USD,69900.83,70014.64,69035.13,69177.77,13.942192,964489.7812

In [85]:
df.loc['']

KeyError: ''